// Generated by gencpp from file dynamixel_driver/DxlArrayMotorHardwareStatus.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_DRIVER_MESSAGE_DXLARRAYMOTORHARDWARESTATUS_H
#define DYNAMIXEL_DRIVER_MESSAGE_DXLARRAYMOTORHARDWARESTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dynamixel_driver/DxlMotorHardwareStatus.h>

namespace dynamixel_driver
{
template <class ContainerAllocator>
struct DxlArrayMotorHardwareStatus_
{
  typedef DxlArrayMotorHardwareStatus_<ContainerAllocator> Type;

  DxlArrayMotorHardwareStatus_()
    : header()
    , motors_hw_status()  {
    }
  DxlArrayMotorHardwareStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motors_hw_status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dynamixel_driver::DxlMotorHardwareStatus_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::dynamixel_driver::DxlMotorHardwareStatus_<ContainerAllocator> >> _motors_hw_status_type;
  _motors_hw_status_type motors_hw_status;





  typedef boost::shared_ptr< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> const> ConstPtr;

}; // struct DxlArrayMotorHardwareStatus_

typedef ::dynamixel_driver::DxlArrayMotorHardwareStatus_<std::allocator<void> > DxlArrayMotorHardwareStatus;

typedef boost::shared_ptr< ::dynamixel_driver::DxlArrayMotorHardwareStatus > DxlArrayMotorHardwareStatusPtr;
typedef boost::shared_ptr< ::dynamixel_driver::DxlArrayMotorHardwareStatus const> DxlArrayMotorHardwareStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator1> & lhs, const ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.motors_hw_status == rhs.motors_hw_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator1> & lhs, const ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f5602f390b032e1f3cb2909956c5381";
  }

  static const char* value(const ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f5602f390b032e1ULL;
  static const uint64_t static_value2 = 0xf3cb2909956c5381ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_driver/DxlArrayMotorHardwareStatus";
  }

  static const char* value(const ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"dynamixel_driver/DxlMotorHardwareStatus[] motors_hw_status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dynamixel_driver/DxlMotorHardwareStatus\n"
"niryo_robot_msgs/MotorHeader motor_identity\n"
"\n"
"uint32 temperature\n"
"float64 voltage\n"
"uint32 error\n"
"string error_msg\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_msgs/MotorHeader\n"
"uint8 motor_id\n"
"\n"
"uint8 motor_type\n"
"uint8 MOTOR_TYPE_STEPPER=1\n"
"uint8 MOTOR_TYPE_XL430=2\n"
"uint8 MOTOR_TYPE_XL320=3\n"
;
  }

  static const char* value(const ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motors_hw_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DxlArrayMotorHardwareStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_driver::DxlArrayMotorHardwareStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motors_hw_status[]" << std::endl;
    for (size_t i = 0; i < v.motors_hw_status.size(); ++i)
    {
      s << indent << "  motors_hw_status[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dynamixel_driver::DxlMotorHardwareStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.motors_hw_status[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_DRIVER_MESSAGE_DXLARRAYMOTORHARDWARESTATUS_H
