// Generated by gencpp from file dynamixel_driver/SendCustomDxlValue.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_DRIVER_MESSAGE_SENDCUSTOMDXLVALUE_H
#define DYNAMIXEL_DRIVER_MESSAGE_SENDCUSTOMDXLVALUE_H

#include <ros/service_traits.h>


#include <dynamixel_driver/SendCustomDxlValueRequest.h>
#include <dynamixel_driver/SendCustomDxlValueResponse.h>


namespace dynamixel_driver
{

struct SendCustomDxlValue
{

typedef SendCustomDxlValueRequest Request;
typedef SendCustomDxlValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendCustomDxlValue
} // namespace dynamixel_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_driver::SendCustomDxlValue > {
  static const char* value()
  {
    return "a6060cddb14becf7546eae23209ccf2a";
  }

  static const char* value(const ::dynamixel_driver::SendCustomDxlValue&) { return value(); }
};

template<>
struct DataType< ::dynamixel_driver::SendCustomDxlValue > {
  static const char* value()
  {
    return "dynamixel_driver/SendCustomDxlValue";
  }

  static const char* value(const ::dynamixel_driver::SendCustomDxlValue&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_driver::SendCustomDxlValueRequest> should match
// service_traits::MD5Sum< ::dynamixel_driver::SendCustomDxlValue >
template<>
struct MD5Sum< ::dynamixel_driver::SendCustomDxlValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_driver::SendCustomDxlValue >::value();
  }
  static const char* value(const ::dynamixel_driver::SendCustomDxlValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_driver::SendCustomDxlValueRequest> should match
// service_traits::DataType< ::dynamixel_driver::SendCustomDxlValue >
template<>
struct DataType< ::dynamixel_driver::SendCustomDxlValueRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_driver::SendCustomDxlValue >::value();
  }
  static const char* value(const ::dynamixel_driver::SendCustomDxlValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_driver::SendCustomDxlValueResponse> should match
// service_traits::MD5Sum< ::dynamixel_driver::SendCustomDxlValue >
template<>
struct MD5Sum< ::dynamixel_driver::SendCustomDxlValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_driver::SendCustomDxlValue >::value();
  }
  static const char* value(const ::dynamixel_driver::SendCustomDxlValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_driver::SendCustomDxlValueResponse> should match
// service_traits::DataType< ::dynamixel_driver::SendCustomDxlValue >
template<>
struct DataType< ::dynamixel_driver::SendCustomDxlValueResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_driver::SendCustomDxlValue >::value();
  }
  static const char* value(const ::dynamixel_driver::SendCustomDxlValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_DRIVER_MESSAGE_SENDCUSTOMDXLVALUE_H
