; Auto-generated. Do not edit!


(cl:in-package niryo_robot_arm_commander-msg)


;//! \htmlinclude RobotMoveFeedback.msg.html

(cl:defclass <RobotMoveFeedback> (roslisp-msg-protocol:ros-message)
  ((state
    :reader state
    :initarg :state
    :type niryo_robot_msgs-msg:RobotState
    :initform (cl:make-instance 'niryo_robot_msgs-msg:RobotState)))
)

(cl:defclass RobotMoveFeedback (<RobotMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RobotMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RobotMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name niryo_robot_arm_commander-msg:<RobotMoveFeedback> is deprecated: use niryo_robot_arm_commander-msg:RobotMoveFeedback instead.")))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <RobotMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader niryo_robot_arm_commander-msg:state-val is deprecated.  Use niryo_robot_arm_commander-msg:state instead.")
  (state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RobotMoveFeedback>) ostream)
  "Serializes a message object of type '<RobotMoveFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'state) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RobotMoveFeedback>) istream)
  "Deserializes a message object of type '<RobotMoveFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'state) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RobotMoveFeedback>)))
  "Returns string type for a message object of type '<RobotMoveFeedback>"
  "niryo_robot_arm_commander/RobotMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RobotMoveFeedback)))
  "Returns string type for a message object of type 'RobotMoveFeedback"
  "niryo_robot_arm_commander/RobotMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RobotMoveFeedback>)))
  "Returns md5sum for a message object of type '<RobotMoveFeedback>"
  "f4863b24a65d1293921d0d4a68f8be4b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RobotMoveFeedback)))
  "Returns md5sum for a message object of type 'RobotMoveFeedback"
  "f4863b24a65d1293921d0d4a68f8be4b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RobotMoveFeedback>)))
  "Returns full string definition for message of type '<RobotMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%niryo_robot_msgs/RobotState state~%~%~%================================================================================~%MSG: niryo_robot_msgs/RobotState~%geometry_msgs/Point position~%niryo_robot_msgs/RPY rpy~%geometry_msgs/Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: niryo_robot_msgs/RPY~%# roll, pitch and yaw~%~%float64 roll~%float64 pitch~%float64 yaw~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RobotMoveFeedback)))
  "Returns full string definition for message of type 'RobotMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%niryo_robot_msgs/RobotState state~%~%~%================================================================================~%MSG: niryo_robot_msgs/RobotState~%geometry_msgs/Point position~%niryo_robot_msgs/RPY rpy~%geometry_msgs/Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: niryo_robot_msgs/RPY~%# roll, pitch and yaw~%~%float64 roll~%float64 pitch~%float64 yaw~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RobotMoveFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'state))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RobotMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RobotMoveFeedback
    (cl:cons ':state (state msg))
))
