(cl:defpackage dynamixel_driver-srv
  (:use )
  (:export
   "SENDCUSTOMDXLVALUE"
   "<SENDCUSTOMDXLVALUE-REQUEST>"
   "SENDCUSTOMDXLVALUE-REQUEST"
   "<SENDCUSTOMDXLVALUE-RESPONSE>"
   "SENDCUSTOMDXLVALUE-RESPONSE"
  ))

