(cl:defpackage dynamixel_driver-msg
  (:use )
  (:export
   "<DXLARRAYMOTORHARDWARESTATUS>"
   "DXLARRAYMOTORHARDWARESTATUS"
   "<DXLMOTORCOMMAND>"
   "DXLMOTORCOMMAND"
   "<DXLMOTORHARDWARESTATUS>"
   "DXLMOTORHARDWARESTATUS"
  ))

