; Auto-generated. Do not edit!


(cl:in-package niryo_robot_tools_commander-msg)


;//! \htmlinclude ToolGoal.msg.html

(cl:defclass <ToolGoal> (roslisp-msg-protocol:ros-message)
  ((cmd
    :reader cmd
    :initarg :cmd
    :type niryo_robot_tools_commander-msg:ToolCommand
    :initform (cl:make-instance 'niryo_robot_tools_commander-msg:ToolCommand)))
)

(cl:defclass ToolGoal (<ToolGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ToolGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ToolGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name niryo_robot_tools_commander-msg:<ToolGoal> is deprecated: use niryo_robot_tools_commander-msg:ToolGoal instead.")))

(cl:ensure-generic-function 'cmd-val :lambda-list '(m))
(cl:defmethod cmd-val ((m <ToolGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader niryo_robot_tools_commander-msg:cmd-val is deprecated.  Use niryo_robot_tools_commander-msg:cmd instead.")
  (cmd m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ToolGoal>) ostream)
  "Serializes a message object of type '<ToolGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'cmd) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ToolGoal>) istream)
  "Deserializes a message object of type '<ToolGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'cmd) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ToolGoal>)))
  "Returns string type for a message object of type '<ToolGoal>"
  "niryo_robot_tools_commander/ToolGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ToolGoal)))
  "Returns string type for a message object of type 'ToolGoal"
  "niryo_robot_tools_commander/ToolGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ToolGoal>)))
  "Returns md5sum for a message object of type '<ToolGoal>"
  "6a82b00a12ace7515f408f53824d53d8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ToolGoal)))
  "Returns md5sum for a message object of type 'ToolGoal"
  "6a82b00a12ace7515f408f53824d53d8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ToolGoal>)))
  "Returns full string definition for message of type '<ToolGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%niryo_robot_tools_commander/ToolCommand cmd~%~%================================================================================~%MSG: niryo_robot_tools_commander/ToolCommand~%# Gripper~%uint8 OPEN_GRIPPER = 1~%uint8 CLOSE_GRIPPER = 2~%~%# Vacuump pump~%uint8 PULL_AIR_VACUUM_PUMP = 10~%uint8 PUSH_AIR_VACUUM_PUMP = 11~%~%# Tools controlled by digital I/Os~%uint8 SETUP_DIGITAL_IO = 20~%uint8 ACTIVATE_DIGITAL_IO = 21~%uint8 DEACTIVATE_DIGITAL_IO = 22~%~%uint8 cmd_type~%~%# Gripper1= 11, Gripper2=12, Gripper3=13, VaccuumPump=31, Electromagnet=30~%uint8 tool_id~%~%# if gripper close~%uint16 gripper_close_speed~%~%# if gripper open~%uint16 gripper_open_speed~%~%# if vacuum pump or electromagnet grove~%bool activate~%~%# if tool is set by digital outputs (electromagnet)~%# if gpio<0 get value in memory~%int8 gpio~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ToolGoal)))
  "Returns full string definition for message of type 'ToolGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%niryo_robot_tools_commander/ToolCommand cmd~%~%================================================================================~%MSG: niryo_robot_tools_commander/ToolCommand~%# Gripper~%uint8 OPEN_GRIPPER = 1~%uint8 CLOSE_GRIPPER = 2~%~%# Vacuump pump~%uint8 PULL_AIR_VACUUM_PUMP = 10~%uint8 PUSH_AIR_VACUUM_PUMP = 11~%~%# Tools controlled by digital I/Os~%uint8 SETUP_DIGITAL_IO = 20~%uint8 ACTIVATE_DIGITAL_IO = 21~%uint8 DEACTIVATE_DIGITAL_IO = 22~%~%uint8 cmd_type~%~%# Gripper1= 11, Gripper2=12, Gripper3=13, VaccuumPump=31, Electromagnet=30~%uint8 tool_id~%~%# if gripper close~%uint16 gripper_close_speed~%~%# if gripper open~%uint16 gripper_open_speed~%~%# if vacuum pump or electromagnet grove~%bool activate~%~%# if tool is set by digital outputs (electromagnet)~%# if gpio<0 get value in memory~%int8 gpio~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ToolGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'cmd))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ToolGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ToolGoal
    (cl:cons ':cmd (cmd msg))
))
