controller_list:
  - name: fake_niryo_robot_follow_joint_trajectory_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gazebo_tool_commander
    joints:
      - joint_base_to_mors_1
      - joint_base_to_mors_2