// Generated by gencpp from file niryo_robot_poses_handlers/ManageTrajectory.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_MANAGETRAJECTORY_H
#define NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_MANAGETRAJECTORY_H

#include <ros/service_traits.h>


#include <niryo_robot_poses_handlers/ManageTrajectoryRequest.h>
#include <niryo_robot_poses_handlers/ManageTrajectoryResponse.h>


namespace niryo_robot_poses_handlers
{

struct ManageTrajectory
{

typedef ManageTrajectoryRequest Request;
typedef ManageTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManageTrajectory
} // namespace niryo_robot_poses_handlers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_poses_handlers::ManageTrajectory > {
  static const char* value()
  {
    return "1546ed78ca405f254ae39431a0854a69";
  }

  static const char* value(const ::niryo_robot_poses_handlers::ManageTrajectory&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_poses_handlers::ManageTrajectory > {
  static const char* value()
  {
    return "niryo_robot_poses_handlers/ManageTrajectory";
  }

  static const char* value(const ::niryo_robot_poses_handlers::ManageTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_poses_handlers::ManageTrajectoryRequest> should match
// service_traits::MD5Sum< ::niryo_robot_poses_handlers::ManageTrajectory >
template<>
struct MD5Sum< ::niryo_robot_poses_handlers::ManageTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_poses_handlers::ManageTrajectory >::value();
  }
  static const char* value(const ::niryo_robot_poses_handlers::ManageTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_poses_handlers::ManageTrajectoryRequest> should match
// service_traits::DataType< ::niryo_robot_poses_handlers::ManageTrajectory >
template<>
struct DataType< ::niryo_robot_poses_handlers::ManageTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_poses_handlers::ManageTrajectory >::value();
  }
  static const char* value(const ::niryo_robot_poses_handlers::ManageTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_poses_handlers::ManageTrajectoryResponse> should match
// service_traits::MD5Sum< ::niryo_robot_poses_handlers::ManageTrajectory >
template<>
struct MD5Sum< ::niryo_robot_poses_handlers::ManageTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_poses_handlers::ManageTrajectory >::value();
  }
  static const char* value(const ::niryo_robot_poses_handlers::ManageTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_poses_handlers::ManageTrajectoryResponse> should match
// service_traits::DataType< ::niryo_robot_poses_handlers::ManageTrajectory >
template<>
struct DataType< ::niryo_robot_poses_handlers::ManageTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_poses_handlers::ManageTrajectory >::value();
  }
  static const char* value(const ::niryo_robot_poses_handlers::ManageTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_MANAGETRAJECTORY_H
