// Generated by gencpp from file stepper_driver/StepperCmd.msg
// DO NOT EDIT!


#ifndef STEPPER_DRIVER_MESSAGE_STEPPERCMD_H
#define STEPPER_DRIVER_MESSAGE_STEPPERCMD_H

#include <ros/service_traits.h>


#include <stepper_driver/StepperCmdRequest.h>
#include <stepper_driver/StepperCmdResponse.h>


namespace stepper_driver
{

struct StepperCmd
{

typedef StepperCmdRequest Request;
typedef StepperCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StepperCmd
} // namespace stepper_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stepper_driver::StepperCmd > {
  static const char* value()
  {
    return "ba19744f08da796611d9a0fb1a26974e";
  }

  static const char* value(const ::stepper_driver::StepperCmd&) { return value(); }
};

template<>
struct DataType< ::stepper_driver::StepperCmd > {
  static const char* value()
  {
    return "stepper_driver/StepperCmd";
  }

  static const char* value(const ::stepper_driver::StepperCmd&) { return value(); }
};


// service_traits::MD5Sum< ::stepper_driver::StepperCmdRequest> should match
// service_traits::MD5Sum< ::stepper_driver::StepperCmd >
template<>
struct MD5Sum< ::stepper_driver::StepperCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stepper_driver::StepperCmd >::value();
  }
  static const char* value(const ::stepper_driver::StepperCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stepper_driver::StepperCmdRequest> should match
// service_traits::DataType< ::stepper_driver::StepperCmd >
template<>
struct DataType< ::stepper_driver::StepperCmdRequest>
{
  static const char* value()
  {
    return DataType< ::stepper_driver::StepperCmd >::value();
  }
  static const char* value(const ::stepper_driver::StepperCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stepper_driver::StepperCmdResponse> should match
// service_traits::MD5Sum< ::stepper_driver::StepperCmd >
template<>
struct MD5Sum< ::stepper_driver::StepperCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stepper_driver::StepperCmd >::value();
  }
  static const char* value(const ::stepper_driver::StepperCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stepper_driver::StepperCmdResponse> should match
// service_traits::DataType< ::stepper_driver::StepperCmd >
template<>
struct DataType< ::stepper_driver::StepperCmdResponse>
{
  static const char* value()
  {
    return DataType< ::stepper_driver::StepperCmd >::value();
  }
  static const char* value(const ::stepper_driver::StepperCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STEPPER_DRIVER_MESSAGE_STEPPERCMD_H
