// Generated by gencpp from file stepper_driver/StepperCmdResponse.msg
// DO NOT EDIT!


#ifndef STEPPER_DRIVER_MESSAGE_STEPPERCMDRESPONSE_H
#define STEPPER_DRIVER_MESSAGE_STEPPERCMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stepper_driver
{
template <class ContainerAllocator>
struct StepperCmdResponse_
{
  typedef StepperCmdResponse_<ContainerAllocator> Type;

  StepperCmdResponse_()
    : result(false)  {
    }
  StepperCmdResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StepperCmdResponse_

typedef ::stepper_driver::StepperCmdResponse_<std::allocator<void> > StepperCmdResponse;

typedef boost::shared_ptr< ::stepper_driver::StepperCmdResponse > StepperCmdResponsePtr;
typedef boost::shared_ptr< ::stepper_driver::StepperCmdResponse const> StepperCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stepper_driver::StepperCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stepper_driver::StepperCmdResponse_<ContainerAllocator1> & lhs, const ::stepper_driver::StepperCmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stepper_driver::StepperCmdResponse_<ContainerAllocator1> & lhs, const ::stepper_driver::StepperCmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stepper_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::stepper_driver::StepperCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stepper_driver/StepperCmdResponse";
  }

  static const char* value(const ::stepper_driver::StepperCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::stepper_driver::StepperCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepperCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stepper_driver::StepperCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stepper_driver::StepperCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEPPER_DRIVER_MESSAGE_STEPPERCMDRESPONSE_H
