// Generated by gencpp from file niryo_robot_serial_number/GetSerial.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_SERIAL_NUMBER_MESSAGE_GETSERIAL_H
#define NIRYO_ROBOT_SERIAL_NUMBER_MESSAGE_GETSERIAL_H

#include <ros/service_traits.h>


#include <niryo_robot_serial_number/GetSerialRequest.h>
#include <niryo_robot_serial_number/GetSerialResponse.h>


namespace niryo_robot_serial_number
{

struct GetSerial
{

typedef GetSerialRequest Request;
typedef GetSerialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSerial
} // namespace niryo_robot_serial_number


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_serial_number::GetSerial > {
  static const char* value()
  {
    return "09803e1f4a40b6f2352e453a75b02d0b";
  }

  static const char* value(const ::niryo_robot_serial_number::GetSerial&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_serial_number::GetSerial > {
  static const char* value()
  {
    return "niryo_robot_serial_number/GetSerial";
  }

  static const char* value(const ::niryo_robot_serial_number::GetSerial&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_serial_number::GetSerialRequest> should match
// service_traits::MD5Sum< ::niryo_robot_serial_number::GetSerial >
template<>
struct MD5Sum< ::niryo_robot_serial_number::GetSerialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_serial_number::GetSerial >::value();
  }
  static const char* value(const ::niryo_robot_serial_number::GetSerialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_serial_number::GetSerialRequest> should match
// service_traits::DataType< ::niryo_robot_serial_number::GetSerial >
template<>
struct DataType< ::niryo_robot_serial_number::GetSerialRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_serial_number::GetSerial >::value();
  }
  static const char* value(const ::niryo_robot_serial_number::GetSerialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_serial_number::GetSerialResponse> should match
// service_traits::MD5Sum< ::niryo_robot_serial_number::GetSerial >
template<>
struct MD5Sum< ::niryo_robot_serial_number::GetSerialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_serial_number::GetSerial >::value();
  }
  static const char* value(const ::niryo_robot_serial_number::GetSerialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_serial_number::GetSerialResponse> should match
// service_traits::DataType< ::niryo_robot_serial_number::GetSerial >
template<>
struct DataType< ::niryo_robot_serial_number::GetSerialResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_serial_number::GetSerial >::value();
  }
  static const char* value(const ::niryo_robot_serial_number::GetSerialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_SERIAL_NUMBER_MESSAGE_GETSERIAL_H
