// Generated by gencpp from file tools_interface/CloseGripper.msg
// DO NOT EDIT!


#ifndef TOOLS_INTERFACE_MESSAGE_CLOSEGRIPPER_H
#define TOOLS_INTERFACE_MESSAGE_CLOSEGRIPPER_H

#include <ros/service_traits.h>


#include <tools_interface/CloseGripperRequest.h>
#include <tools_interface/CloseGripperResponse.h>


namespace tools_interface
{

struct CloseGripper
{

typedef CloseGripperRequest Request;
typedef CloseGripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CloseGripper
} // namespace tools_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tools_interface::CloseGripper > {
  static const char* value()
  {
    return "04901e0d312f8ee9c675fc0042c3a8e4";
  }

  static const char* value(const ::tools_interface::CloseGripper&) { return value(); }
};

template<>
struct DataType< ::tools_interface::CloseGripper > {
  static const char* value()
  {
    return "tools_interface/CloseGripper";
  }

  static const char* value(const ::tools_interface::CloseGripper&) { return value(); }
};


// service_traits::MD5Sum< ::tools_interface::CloseGripperRequest> should match
// service_traits::MD5Sum< ::tools_interface::CloseGripper >
template<>
struct MD5Sum< ::tools_interface::CloseGripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tools_interface::CloseGripper >::value();
  }
  static const char* value(const ::tools_interface::CloseGripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tools_interface::CloseGripperRequest> should match
// service_traits::DataType< ::tools_interface::CloseGripper >
template<>
struct DataType< ::tools_interface::CloseGripperRequest>
{
  static const char* value()
  {
    return DataType< ::tools_interface::CloseGripper >::value();
  }
  static const char* value(const ::tools_interface::CloseGripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tools_interface::CloseGripperResponse> should match
// service_traits::MD5Sum< ::tools_interface::CloseGripper >
template<>
struct MD5Sum< ::tools_interface::CloseGripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tools_interface::CloseGripper >::value();
  }
  static const char* value(const ::tools_interface::CloseGripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tools_interface::CloseGripperResponse> should match
// service_traits::DataType< ::tools_interface::CloseGripper >
template<>
struct DataType< ::tools_interface::CloseGripperResponse>
{
  static const char* value()
  {
    return DataType< ::tools_interface::CloseGripper >::value();
  }
  static const char* value(const ::tools_interface::CloseGripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOOLS_INTERFACE_MESSAGE_CLOSEGRIPPER_H
