// Generated by gencpp from file tools_interface/PullAirVacuumPump.msg
// DO NOT EDIT!


#ifndef TOOLS_INTERFACE_MESSAGE_PULLAIRVACUUMPUMP_H
#define TOOLS_INTERFACE_MESSAGE_PULLAIRVACUUMPUMP_H

#include <ros/service_traits.h>


#include <tools_interface/PullAirVacuumPumpRequest.h>
#include <tools_interface/PullAirVacuumPumpResponse.h>


namespace tools_interface
{

struct PullAirVacuumPump
{

typedef PullAirVacuumPumpRequest Request;
typedef PullAirVacuumPumpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PullAirVacuumPump
} // namespace tools_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tools_interface::PullAirVacuumPump > {
  static const char* value()
  {
    return "fdd48b46d71dd8ff507dc76750227fa6";
  }

  static const char* value(const ::tools_interface::PullAirVacuumPump&) { return value(); }
};

template<>
struct DataType< ::tools_interface::PullAirVacuumPump > {
  static const char* value()
  {
    return "tools_interface/PullAirVacuumPump";
  }

  static const char* value(const ::tools_interface::PullAirVacuumPump&) { return value(); }
};


// service_traits::MD5Sum< ::tools_interface::PullAirVacuumPumpRequest> should match
// service_traits::MD5Sum< ::tools_interface::PullAirVacuumPump >
template<>
struct MD5Sum< ::tools_interface::PullAirVacuumPumpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tools_interface::PullAirVacuumPump >::value();
  }
  static const char* value(const ::tools_interface::PullAirVacuumPumpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tools_interface::PullAirVacuumPumpRequest> should match
// service_traits::DataType< ::tools_interface::PullAirVacuumPump >
template<>
struct DataType< ::tools_interface::PullAirVacuumPumpRequest>
{
  static const char* value()
  {
    return DataType< ::tools_interface::PullAirVacuumPump >::value();
  }
  static const char* value(const ::tools_interface::PullAirVacuumPumpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tools_interface::PullAirVacuumPumpResponse> should match
// service_traits::MD5Sum< ::tools_interface::PullAirVacuumPump >
template<>
struct MD5Sum< ::tools_interface::PullAirVacuumPumpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tools_interface::PullAirVacuumPump >::value();
  }
  static const char* value(const ::tools_interface::PullAirVacuumPumpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tools_interface::PullAirVacuumPumpResponse> should match
// service_traits::DataType< ::tools_interface::PullAirVacuumPump >
template<>
struct DataType< ::tools_interface::PullAirVacuumPumpResponse>
{
  static const char* value()
  {
    return DataType< ::tools_interface::PullAirVacuumPump >::value();
  }
  static const char* value(const ::tools_interface::PullAirVacuumPumpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOOLS_INTERFACE_MESSAGE_PULLAIRVACUUMPUMP_H
