// Generated by gencpp from file tools_interface/PushAirVacuumPump.msg
// DO NOT EDIT!


#ifndef TOOLS_INTERFACE_MESSAGE_PUSHAIRVACUUMPUMP_H
#define TOOLS_INTERFACE_MESSAGE_PUSHAIRVACUUMPUMP_H

#include <ros/service_traits.h>


#include <tools_interface/PushAirVacuumPumpRequest.h>
#include <tools_interface/PushAirVacuumPumpResponse.h>


namespace tools_interface
{

struct PushAirVacuumPump
{

typedef PushAirVacuumPumpRequest Request;
typedef PushAirVacuumPumpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PushAirVacuumPump
} // namespace tools_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tools_interface::PushAirVacuumPump > {
  static const char* value()
  {
    return "41cc870230024f471ead928a5e8205a0";
  }

  static const char* value(const ::tools_interface::PushAirVacuumPump&) { return value(); }
};

template<>
struct DataType< ::tools_interface::PushAirVacuumPump > {
  static const char* value()
  {
    return "tools_interface/PushAirVacuumPump";
  }

  static const char* value(const ::tools_interface::PushAirVacuumPump&) { return value(); }
};


// service_traits::MD5Sum< ::tools_interface::PushAirVacuumPumpRequest> should match
// service_traits::MD5Sum< ::tools_interface::PushAirVacuumPump >
template<>
struct MD5Sum< ::tools_interface::PushAirVacuumPumpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tools_interface::PushAirVacuumPump >::value();
  }
  static const char* value(const ::tools_interface::PushAirVacuumPumpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tools_interface::PushAirVacuumPumpRequest> should match
// service_traits::DataType< ::tools_interface::PushAirVacuumPump >
template<>
struct DataType< ::tools_interface::PushAirVacuumPumpRequest>
{
  static const char* value()
  {
    return DataType< ::tools_interface::PushAirVacuumPump >::value();
  }
  static const char* value(const ::tools_interface::PushAirVacuumPumpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tools_interface::PushAirVacuumPumpResponse> should match
// service_traits::MD5Sum< ::tools_interface::PushAirVacuumPump >
template<>
struct MD5Sum< ::tools_interface::PushAirVacuumPumpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tools_interface::PushAirVacuumPump >::value();
  }
  static const char* value(const ::tools_interface::PushAirVacuumPumpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tools_interface::PushAirVacuumPumpResponse> should match
// service_traits::DataType< ::tools_interface::PushAirVacuumPump >
template<>
struct DataType< ::tools_interface::PushAirVacuumPumpResponse>
{
  static const char* value()
  {
    return DataType< ::tools_interface::PushAirVacuumPump >::value();
  }
  static const char* value(const ::tools_interface::PushAirVacuumPumpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOOLS_INTERFACE_MESSAGE_PUSHAIRVACUUMPUMP_H
