(cl:defpackage niryo_robot_rpi-srv
  (:use )
  (:export
   "CHANGEMOTORCONFIG"
   "<CHANGEMOTORCONFIG-REQUEST>"
   "CHANGEMOTORCONFIG-REQUEST"
   "<CHANGEMOTORCONFIG-RESPONSE>"
   "CHANGEMOTORCONFIG-RESPONSE"
   "GETDIGITALIO"
   "<GETDIGITALIO-REQUEST>"
   "GETDIGITALIO-REQUEST"
   "<GETDIGITALIO-RESPONSE>"
   "GETDIGITALIO-RESPONSE"
   "LEDBLINKER"
   "<LEDBLINKER-REQUEST>"
   "LEDBLINKER-REQUEST"
   "<LEDBLINKER-RESPONSE>"
   "LEDBLINKER-RESPONSE"
   "SETDIGITALIO"
   "<SETDIGITALIO-REQUEST>"
   "SETDIGITALIO-REQUEST"
   "<SETDIGITALIO-RESPONSE>"
   "SETDIGITALIO-RESPONSE"
  ))

